---
- name: MariaDBのインストール
  tags: mariadb
  become: yes
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: '{{ apt_update_cache_valid_time }}'
    name:
      - mariadb-server

- name: MariaDB 起動
  tags: mariadb
  ansible.builtin.systemd:
    name: mariadb
    state: started

# 自分でやる
# sudo su -
# mysql
# https://www.digitalocean.com/community/tutorials/how-to-install-mariadb-on-ubuntu-20-04-ja#2-mariadb
# passwordの方は適宜変更する
# GRANT ALL ON *.* TO admin@'%' IDENTIFIED BY 'your_password' WITH GRANT OPTION;
# GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'your_password' WITH GRANT OPTION;
# SELECT User, Host, authentication_string FROM mysql.user;
# FLUSH PRIVILEGES;
# DROP USER 'root'@'%';

# rootでlogin
# ```sql
# create database app;
# create user 'app'@'%' identified by 'your_password';
# grant all privileges on app.* to 'app'@'%';
# flush privileges;
# show grants for 'app'@'%';
# show variables like '%collation%';
# select default_collation_name from information_schema.schemata where schema_name = 'app';
# ```
# 何もしなかったらデフォ「utf8mb4_general_ci」となる

# Rails
# bundle exec rails new app -d mysql --skip-bundle
# cd app
# rm config/database.yaml
# export DATABASE_URL=mysql2://app:your_password@localhost:3306/app
# bundle exec rails s -b 0.0.0.0

#- name: Securing MariaDB
#  tags: mariadb
#  become: true
#  ansible.builtin.expect:
#    command: mysql_secure_installation
#    responses:
#      'Enter current password for root \(enter for none\): ': '' # 現在のパスワード、ない場合は空文字を入力
#      'Switch to unix_socket authentication \[Y\/n\] ': 'n' # unix_socket認証を使うかどうか
#      'Change the root password\? \[Y\/n\] ': 'y' # rootのパスワードを変更するかどうか
#      'New password:': "{{ db_root_user_pass }}" # 新しいパスワード
#      'Re-enter new password:': "{{ db_root_user_pass }}" # 新しいパスワードの再入力
#      'Remove anonymous users\? \[Y\/n\]': 'y' # 匿名ユーザーを削除するかどうか
#      'Disallow root login remotely\? \[Y\/n\]': 'n' # rootユーザーのリモートログインを不許可するかどうか(n = 許可)
#      'Remove test database and access to it\? \[Y\/n\]': 'y' # テストデータベースを削除するかどうか
#      'Reload privilege tables now\? \[Y\/n\]': 'y' # 権限テーブルを再読み込みするかどうか
#
- name: MariaDBに対して、リモート接続を許可する
  tags: mariadb
  become: yes
  ansible.builtin.lineinfile:
    mode: "0644"
    path: "{{ item.dir }}"
    regexp: "^bind-address"
    create: true
    line: "bind-address  = 0.0.0.0"
  with_items:
    - { dir: "/etc/mysql/mariadb.conf.d/50-server.cnf" }

- name: Restarting MariaDB
  tags: mariadb
  become: yes
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
