---

services:
  ansible:
    build: .
    working_dir: /ansible/
    volumes:
      - type: bind
        source: ${PWD}/ansible/
        target: /ansible/
      - type: bind
        source: ${HOME}/.ssh/
        target: /root/.ssh/
      - type: bind
        source: ${PWD}/tmp/ansible-log/
        target: /var/log/ansible-log/
    env_file:
      - .env
