---

services:
  ansible:
    build: .
    working_dir: /ansible/
    volumes:
      - type: bind
        source: ${PWD}/ansible/
        target: /ansible/
      - type: bind
        source: ${HOME}/.ssh/
        target: /root/.ssh/
    env_file:
      - .env
