---
- name: aptで共通して入れる(neovim, curl, git, tmux等)
  become: yes
  tags: common
  ansible.builtin.apt:
    state: present
    update_cache: true
    install_recommends: no
    cache_valid_time: '{{ apt_update_cache_valid_time }}'
    name:
      - neovim
      - curl
      - git
      - tmux
      - tree
      - jq
      - psmisc
      - make
