---
- name: aptで共通して入れる(neovim, curl, git, tmux等)
  become: yes
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - neovim
      - curl
      - git
      - tmux
      - tree
      - jq
      - psmisc

- name: webユーザーを追加
  become: yes
  ansible.builtin.user:
    name: web
    state: present
    shell: /bin/bash
    #shell: /usr/sbin/nologin