---
ansible_ssh_user: "{{ lookup('ansible.builtin.env', 'ANSIBLE_SSH_USER') }}"
ansible_ssh_private_key_file: "{{ lookup('ansible.builtin.env', 'ANSIBLE_SSH_PRIVATE_KEY_FILE') }}"

# apt updateのキャッシュの有効時間(秒)
apt_update_cache_valid_time: 3600

# newrelicのLICENSE APIキー
newrelic_license_key: "{{ lookup('ansible.builtin.env', 'NEWRELIC_LICENSE_KEY') }}"
