---

services:
  mysql:
    image: mysql:8.4.2
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
      - type: bind
        source: ${PWD}/sql/
        target: /sql/
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
  redis:
    image: redis:7.4.0-bookworm
    ports:
      - 6379:6379

volumes:
  mysql_data:
