---
ansible_ssh_user: "{{ lookup('ansible.builtin.env', 'ANSIBLE_SSH_USER') }}"
ansible_ssh_private_key_file: "{{ lookup('ansible.builtin.env', 'ANSIBLE_SSH_PRIVATE_KEY_FILE') }}"

# apt updateのキャッシュの有効時間(秒)
apt_update_cache_valid_time: 3600

# asdf, asdfを利用するユーザー用
asdf_user: app
asdf_user_home: /home/app
asdf_version: v0.14.0
asdf_ruby_version: 3.3.3
asdf_nodejs_version: 22.3.0
