---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/orders":
    post:
      summary: create order
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
  "/orders/new":
    get:
      summary: new order
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
  "/orders/{id}":
    parameters:
    - name: id
      in: path
      description: 注文のid
      example: 123
      required: true
      schema:
        type: integer
    get:
      summary: show order
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
  "/":
    get:
      summary: show welcome
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  list:
                    type: array
                    items:
                      type: string
                  time:
                    type: string
                    example: '2024-01-01T12:34:56.789+09:00'
                required:
                - message
                - list
                - time
servers:
- url: http://localhost:3000
