source "https://rubygems.org"

gem "rails", "~> 7.1"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

# END-ほぼデフォルト(tz-infoを削除)
# START-自分で追加

group :test do
  gem "rspec-rails"
  gem "json_spec"
end
gem "rswag"
# gem "rack-cors"
